### ISSUE TITLE
Why `-self.logp` ?

### ISSUE THREAD

**Issue by MaverickMeerkat** [gpapamak/snl#2]
https://github.com/gpapamak/snl/blob/51815311fdef53fedfa71cc94593582d7600fc41/ml/models/mades.py#L289

`self.u` should be standard normal. Not sure I understand why the minus `self.logp` in the likelihood calculation.

**Comment by MaverickMeerkat** [comment]
Never mind - I realize now you are calculating the `log p(x_1)p(x_2|x_1)...` and so it works out. You simply replace `u_d = (x_d - \mu(x_<d)/\sigma(x_<d)` you still have to account for the extra `-0.5log \sigma(x_<d)^2` and the `2pi` constants.

**Comment by gpapamak** [comment]
You're right that `self.u` follows a standard normal, but the likelihood is the probability density of `self.inputs` not of `self.u`. `self.inputs` follows a normal with mean `self.m` and log precision `self.logp`, and that's what this line computes.
