### ISSUE TITLE
Confusion about conditional MADE

### ISSUE THREAD

**Issue by MaverickMeerkat** [gpapamak/snl#3]
https://github.com/gpapamak/snl/blob/51815311fdef53fedfa71cc94593582d7600fc41/ml/models/mades.py#L642

I wonder if you are modelling `p(x|y)` ? If so, why is the `y` multiplied by the masking? In the MAF paper you write that "In masked autoregressive models, no connections need to be dropped from the y inputs to the rest of the network." 

Is the `y` actually `self.input` and `x` actually the `self.y`?  

Assuming it is - even though it goes unmasked to the 1st hidden layer, from there on it is masked to the next hidden layers... and so the final layer does have restrictions over the `y`'s. Is that correct? Wouldn't it better to add it to the final hidden layer instead? Or create a complete unmasked network for it?

**Comment by MaverickMeerkat** [comment]
So yeah, I think it's pretty obvious you do `p(y|input)`, i.e. input is the unchanged conditioned, and `y` is the actual variable.

**Comment by gpapamak** [comment]
Correct, this computes `p(y|input)` (sorry, the names are confusing).
